<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsurerSeeder extends Seeder
{
    /**
     * Seed all 30 Spanish health insurers.
     */
    public function run(): void
    {
        $insurers = [
            [
                'name' => 'Adeslas',
                'slug' => 'adeslas',
                'brand_color' => '#009DDC',
                'website_url' => 'https://www.segurcaixaadeslas.es',
                'description' => 'Adeslas (SegurCaixa Adeslas) es la compañía líder en seguros de salud en España, con más de 8 millones de asegurados. Ofrece el cuadro médico más amplio del país con acceso a más de 44.000 profesionales sanitarios y 1.400 centros médicos.',
                'meta_title' => 'Cuadro Médico Adeslas 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Adeslas 2026. Encuentra médicos, especialistas, centros de salud y hospitales de SegurCaixa Adeslas por provincia.',
                'sort_order' => 1,
            ],
            [
                'name' => 'Sanitas',
                'slug' => 'sanitas',
                'brand_color' => '#0079C8',
                'website_url' => 'https://www.sanitas.es',
                'description' => 'Sanitas es una de las principales aseguradoras de salud en España, perteneciente al grupo internacional Bupa. Cuenta con una amplia red de centros propios, hospitales y clínicas dentales, además de una potente plataforma de telemedicina y servicios digitales de salud.',
                'meta_title' => 'Cuadro Médico Sanitas 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Sanitas 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Sanitas en tu provincia.',
                'sort_order' => 2,
            ],
            [
                'name' => 'Asisa',
                'slug' => 'asisa',
                'brand_color' => '#1D4A8D',
                'website_url' => 'https://www.asisa.es',
                'description' => 'ASISA es una cooperativa sanitaria fundada en 1971 y una de las mayores aseguradoras de salud de España. Destaca por su modelo de gestión cooperativo de profesionales médicos, ofreciendo una amplia cobertura en todo el territorio nacional con hospitales del grupo HLA.',
                'meta_title' => 'Cuadro Médico Asisa 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Asisa 2026. Encuentra médicos, especialistas, hospitales HLA y centros sanitarios de ASISA por provincia.',
                'sort_order' => 3,
            ],
            [
                'name' => 'DKV',
                'slug' => 'dkv',
                'brand_color' => '#85A20A',
                'website_url' => 'https://www.dkvseguros.com',
                'description' => 'DKV Seguros, perteneciente al grupo alemán ERGO/Munich Re, es una aseguradora de salud comprometida con la sostenibilidad y la salud integral. Ofrece productos innovadores con especial énfasis en bienestar, prevención y salud digital, con cobertura en toda España.',
                'meta_title' => 'Cuadro Médico DKV 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de DKV Seguros 2026. Encuentra médicos, especialistas, centros de salud y hospitales de DKV en tu provincia.',
                'sort_order' => 4,
            ],
            [
                'name' => 'Mapfre',
                'slug' => 'mapfre',
                'brand_color' => '#C10003',
                'website_url' => 'https://www.mapfre.es',
                'description' => 'MAPFRE Salud es la división de seguros de salud del grupo MAPFRE, la mayor aseguradora española a nivel global. Ofrece seguros de salud con una extensa red médica en todas las provincias de España, complementando su amplia oferta de seguros generales.',
                'meta_title' => 'Cuadro Médico Mapfre 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Mapfre Salud 2026. Encuentra médicos, especialistas, hospitales y centros de salud de MAPFRE por provincia.',
                'sort_order' => 5,
            ],
            [
                'name' => 'Aegon',
                'slug' => 'aegon',
                'brand_color' => '#1377C5',
                'website_url' => 'https://www.aegon.es',
                'description' => 'Aegon Seguros es la filial española del grupo internacional holandés Aegon. Ofrece seguros de salud con una buena relación calidad-precio, con acceso a una amplia red de profesionales médicos y centros sanitarios en las principales provincias de España.',
                'meta_title' => 'Cuadro Médico Aegon 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Aegon 2026. Encuentra médicos, especialistas, centros de salud y hospitales de Aegon Seguros por provincia.',
                'sort_order' => 6,
            ],
            [
                'name' => 'Asefa',
                'slug' => 'asefa',
                'brand_color' => '#002B93',
                'website_url' => 'https://www.asefa.es',
                'description' => 'Asefa Seguros es una aseguradora española con más de 80 años de experiencia en el sector. Ofrece seguros de salud con coberturas competitivas y una red médica en continuo crecimiento, orientada a ofrecer un servicio cercano y personalizado.',
                'meta_title' => 'Cuadro Médico Asefa 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Asefa 2026. Encuentra médicos, especialistas, centros sanitarios y hospitales de Asefa Seguros por provincia.',
                'sort_order' => 7,
            ],
            [
                'name' => 'AXA',
                'slug' => 'axa',
                'brand_color' => '#022064',
                'website_url' => 'https://www.axa.es',
                'description' => 'AXA Salud es la división sanitaria del grupo francés AXA, uno de los mayores grupos aseguradores del mundo. En España ofrece seguros de salud con coberturas completas y acceso a una amplia red de profesionales médicos, hospitales y centros especializados.',
                'meta_title' => 'Cuadro Médico AXA 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de AXA Salud 2026. Encuentra médicos, especialistas, hospitales y centros de salud de AXA en tu provincia.',
                'sort_order' => 8,
            ],
            [
                'name' => 'Antares',
                'slug' => 'antares',
                'brand_color' => '#052B3B',
                'website_url' => 'https://www.antaressalud.es',
                'description' => 'Antares es una aseguradora de salud que opera principalmente en la zona del Levante español. Ofrece seguros médicos con un enfoque regional, garantizando una atención sanitaria de calidad con profesionales y centros de confianza en su área de cobertura.',
                'meta_title' => 'Cuadro Médico Antares 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Antares 2026. Encuentra médicos, especialistas y centros de salud de Antares Salud por provincia.',
                'sort_order' => 9,
            ],
            [
                'name' => 'Caser',
                'slug' => 'caser',
                'brand_color' => '#007361',
                'website_url' => 'https://www.caser.es',
                'description' => 'Caser Seguros es una aseguradora española que forma parte del grupo suizo Helvetia. Su división de salud ofrece seguros médicos con una red propia de centros y residencias, además de acceso a miles de profesionales sanitarios en toda España.',
                'meta_title' => 'Cuadro Médico Caser 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Caser Salud 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Caser por provincia.',
                'sort_order' => 10,
            ],
            [
                'name' => 'Generali',
                'slug' => 'generali',
                'brand_color' => '#FE1E14',
                'website_url' => 'https://www.generali.es',
                'description' => 'Generali es una de las mayores compañías de seguros del mundo, con sede en Italia. En España ofrece seguros de salud con coberturas amplias y una extensa red médica, respaldada por la solidez financiera y experiencia de un grupo con más de 190 años de historia.',
                'meta_title' => 'Cuadro Médico Generali 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Generali 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Generali Seguros por provincia.',
                'sort_order' => 11,
            ],
            [
                'name' => 'Cigna',
                'slug' => 'cigna',
                'brand_color' => '#0082C9',
                'website_url' => 'https://www.cigna.es',
                'description' => 'Cigna Healthcare es la filial española de la multinacional estadounidense The Cigna Group. Especializada en seguros de salud para particulares y empresas, destaca por su enfoque en bienestar integral, programas de prevención y una amplia red médica nacional.',
                'meta_title' => 'Cuadro Médico Cigna 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Cigna Healthcare 2026. Encuentra médicos, especialistas, centros de salud y hospitales de Cigna por provincia.',
                'sort_order' => 12,
            ],
            [
                'name' => 'Agrupació Mutua',
                'slug' => 'agrupacio-mutua',
                'brand_color' => '#00785D',
                'website_url' => 'https://www.agrupaciomutua.es',
                'description' => 'Agrupació Mutua es una mutua de seguros con sede en Barcelona y larga tradición en Cataluña. Ofrece seguros de salud con una red médica especialmente fuerte en la comunidad catalana, proporcionando atención sanitaria de calidad a sus mutualistas.',
                'meta_title' => 'Cuadro Médico Agrupació Mutua 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Agrupació Mutua 2026. Encuentra médicos, especialistas y centros de salud de Agrupació Mutua por provincia.',
                'sort_order' => 13,
            ],
            [
                'name' => 'Catalana Occidente',
                'slug' => 'catalana-occidente',
                'brand_color' => '#838383',
                'website_url' => 'https://www.catalanaoccidente.com',
                'description' => 'Catalana Occidente es uno de los grupos aseguradores más importantes de España, con más de 150 años de historia. Su división de salud ofrece seguros médicos con coberturas sólidas y acceso a una red de profesionales y centros sanitarios en todo el territorio nacional.',
                'meta_title' => 'Cuadro Médico Catalana Occidente 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Catalana Occidente 2026. Encuentra médicos, especialistas y centros de salud de Catalana Occidente por provincia.',
                'sort_order' => 14,
            ],
            [
                'name' => 'Cosalud',
                'slug' => 'cosalud',
                'brand_color' => '#00A0E3',
                'website_url' => 'https://www.cosalud.es',
                'description' => 'Cosalud es una marca de seguros de salud que opera bajo el paraguas de grandes aseguradoras. Ofrece productos de salud asequibles con coberturas esenciales, orientados a personas que buscan un seguro médico básico con buena relación calidad-precio.',
                'meta_title' => 'Cuadro Médico Cosalud 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Cosalud 2026. Encuentra médicos, especialistas, centros de salud y hospitales de Cosalud por provincia.',
                'sort_order' => 15,
            ],
            [
                'name' => 'FIATC',
                'slug' => 'fiatc',
                'brand_color' => '#004B87',
                'website_url' => 'https://www.fiatc.es',
                'description' => 'FIATC Seguros es una mutua de seguros fundada en Barcelona en 1930. Ofrece seguros de salud con una fuerte presencia en Cataluña y cobertura nacional, destacando por su cercanía al asegurado y una red médica de profesionales de confianza.',
                'meta_title' => 'Cuadro Médico FIATC 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de FIATC Seguros 2026. Encuentra médicos, especialistas, hospitales y centros de salud de FIATC por provincia.',
                'sort_order' => 16,
            ],
            [
                'name' => 'HNA',
                'slug' => 'hna',
                'brand_color' => '#003366',
                'website_url' => 'https://www.hna.es',
                'description' => 'HNA (Hermandad Nacional de Arquitectos) es una mutualidad profesional que ofrece seguros de salud destinados principalmente a arquitectos y sus familias. Dispone de un cuadro médico amplio con cobertura nacional y condiciones ventajosas para sus mutualistas.',
                'meta_title' => 'Cuadro Médico HNA 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de HNA 2026. Encuentra médicos, especialistas y centros de salud de la Hermandad Nacional de Arquitectos por provincia.',
                'sort_order' => 17,
            ],
            [
                'name' => 'Igualatorio Cantabria',
                'slug' => 'igualatorio-cantabria',
                'brand_color' => '#1A5632',
                'website_url' => 'https://www.igualatoriocantabria.es',
                'description' => 'Igualatorio Cantabria es una entidad aseguradora de salud con fuerte arraigo en Cantabria. Ofrece seguros médicos con una red de profesionales y centros especialmente densa en la comunidad cántabra, proporcionando atención cercana y de calidad a sus asegurados.',
                'meta_title' => 'Cuadro Médico Igualatorio Cantabria 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Igualatorio Cantabria 2026. Encuentra médicos, especialistas y centros de salud en Cantabria y otras provincias.',
                'sort_order' => 18,
            ],
            [
                'name' => 'IMQ',
                'slug' => 'imq',
                'brand_color' => '#003C71',
                'website_url' => 'https://www.imq.es',
                'description' => 'IMQ (Igualatorio Médico Quirúrgico) es la aseguradora de salud líder en el País Vasco, con más de 80 años de experiencia. Cuenta con centros y hospitales propios en Euskadi, ofreciendo una de las redes sanitarias más completas del norte de España.',
                'meta_title' => 'Cuadro Médico IMQ 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de IMQ 2026. Encuentra médicos, especialistas, hospitales y centros de salud de IMQ en el País Vasco y otras provincias.',
                'sort_order' => 19,
            ],
            [
                'name' => 'MUSA',
                'slug' => 'musa',
                'brand_color' => '#0054A6',
                'website_url' => 'https://www.musa.es',
                'description' => 'MUSA (Mutualidad de Seguros de Arquitectos) es una mutualidad profesional del sector de la arquitectura. Ofrece seguros de salud con condiciones específicas para arquitectos técnicos y profesionales del sector, con una red médica de cobertura nacional.',
                'meta_title' => 'Cuadro Médico MUSA 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de MUSA 2026. Encuentra médicos, especialistas y centros de salud de la Mutualidad de Seguros de Arquitectos.',
                'sort_order' => 20,
            ],
            [
                'name' => 'Néctar',
                'slug' => 'nectar',
                'brand_color' => '#E87722',
                'website_url' => 'https://www.nectarseguros.com',
                'description' => 'Néctar Seguros es una aseguradora de salud española que forma parte del Grupo Catalana Occidente. Ofrece seguros médicos con coberturas flexibles y una red sanitaria amplia, orientados a familias y particulares que buscan un seguro de salud completo y accesible.',
                'meta_title' => 'Cuadro Médico Néctar 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Néctar Seguros 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Néctar por provincia.',
                'sort_order' => 21,
            ],
            [
                'name' => 'NorteHispana',
                'slug' => 'nortehispana',
                'brand_color' => '#004E9A',
                'website_url' => 'https://www.nortehispana.com',
                'description' => 'NorteHispana Seguros es una aseguradora de salud integrada en el Grupo Catalana Occidente. Con presencia destacada en el norte de España, ofrece seguros médicos con amplias coberturas y una red de profesionales sanitarios de confianza en todo el territorio nacional.',
                'meta_title' => 'Cuadro Médico NorteHispana 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de NorteHispana 2026. Encuentra médicos, especialistas y centros de salud de NorteHispana Seguros por provincia.',
                'sort_order' => 22,
            ],
            [
                'name' => 'Plus Ultra',
                'slug' => 'plus-ultra',
                'brand_color' => '#002D72',
                'website_url' => 'https://www.plusultra.es',
                'description' => 'Plus Ultra Seguros es una compañía aseguradora española perteneciente al grupo Catalana Occidente. Ofrece seguros de salud con coberturas adaptadas a diferentes perfiles, respaldados por una red médica nacional y la solidez de uno de los principales grupos aseguradores del país.',
                'meta_title' => 'Cuadro Médico Plus Ultra 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Plus Ultra 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Plus Ultra Seguros por provincia.',
                'sort_order' => 23,
            ],
            [
                'name' => 'Previsora General',
                'slug' => 'previsora-general',
                'brand_color' => '#8B1A1A',
                'website_url' => 'https://www.previsorageneral.com',
                'description' => 'Previsora General es una mutua de seguros con sede en Barcelona y más de 100 años de historia. Ofrece seguros de salud con especial implantación en Cataluña, destacando por su atención personalizada y una red médica de profesionales seleccionados.',
                'meta_title' => 'Cuadro Médico Previsora General 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Previsora General 2026. Encuentra médicos, especialistas y centros de salud de Previsora General por provincia.',
                'sort_order' => 24,
            ],
            [
                'name' => 'Seguros Bilbao',
                'slug' => 'seguros-bilbao',
                'brand_color' => '#003D7C',
                'website_url' => 'https://www.segurosbilbao.com',
                'description' => 'Seguros Bilbao es una aseguradora perteneciente al Grupo Catalana Occidente con fuerte presencia en el norte de España. Ofrece seguros de salud con coberturas completas y una red médica amplia, combinando tradición y servicio cercano con la respaldo de un gran grupo asegurador.',
                'meta_title' => 'Cuadro Médico Seguros Bilbao 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Seguros Bilbao 2026. Encuentra médicos, especialistas y centros de salud de Seguros Bilbao por provincia.',
                'sort_order' => 25,
            ],
            [
                'name' => 'Unión Madrileña',
                'slug' => 'union-madrilena',
                'brand_color' => '#1B3A5C',
                'website_url' => 'https://www.unionmadrilena.es',
                'description' => 'Unión Madrileña de Seguros es una aseguradora de salud con implantación en la Comunidad de Madrid y otras provincias. Ofrece seguros médicos con coberturas ajustadas y una red sanitaria de calidad, con especial foco en la atención personalizada al asegurado.',
                'meta_title' => 'Cuadro Médico Unión Madrileña 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Unión Madrileña 2026. Encuentra médicos, especialistas y centros de salud de Unión Madrileña por provincia.',
                'sort_order' => 26,
            ],
            [
                'name' => 'Vivaz',
                'slug' => 'vivaz',
                'brand_color' => '#FF6B00',
                'website_url' => 'https://www.vivaz.com',
                'description' => 'Vivaz es la marca de seguros de salud digital de Línea Directa Aseguradora. Pensada para un público joven y digital, ofrece seguros de salud 100% online con precios competitivos, gestión a través de app y acceso a una amplia red de profesionales médicos.',
                'meta_title' => 'Cuadro Médico Vivaz 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Vivaz 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Vivaz Seguros por provincia.',
                'sort_order' => 27,
            ],
            [
                'name' => 'Zurich',
                'slug' => 'zurich',
                'brand_color' => '#003399',
                'website_url' => 'https://www.zurich.es',
                'description' => 'Zurich Seguros es la filial española del grupo suizo Zurich Insurance Group, uno de los mayores grupos aseguradores del mundo. Su división de salud ofrece seguros médicos con coberturas internacionales y acceso a una red médica de calidad en toda España.',
                'meta_title' => 'Cuadro Médico Zurich 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Zurich 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Zurich Seguros por provincia.',
                'sort_order' => 28,
            ],
            [
                'name' => 'Allianz',
                'slug' => 'allianz',
                'brand_color' => '#003781',
                'website_url' => 'https://www.allianz.es',
                'description' => 'Allianz es uno de los mayores grupos aseguradores del mundo, con sede en Alemania. En España ofrece seguros de salud con coberturas integrales y una amplia red de profesionales médicos y centros sanitarios, respaldados por la solidez y experiencia de un líder global.',
                'meta_title' => 'Cuadro Médico Allianz 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de Allianz 2026. Encuentra médicos, especialistas, hospitales y centros de salud de Allianz Seguros por provincia.',
                'sort_order' => 29,
            ],
            [
                'name' => 'ACUNSA',
                'slug' => 'acunsa',
                'brand_color' => '#004F9F',
                'website_url' => 'https://www.acunsa.es',
                'description' => 'ACUNSA (Asistencia Clínica Universidad de Navarra) es una aseguradora de salud vinculada a la Clínica Universidad de Navarra. Ofrece seguros médicos con acceso a uno de los hospitales más prestigiosos de España, combinando asistencia sanitaria de excelencia con cobertura nacional.',
                'meta_title' => 'Cuadro Médico ACUNSA 2026 - Médicos y Centros',
                'meta_description' => 'Consulta el cuadro médico de ACUNSA 2026. Encuentra médicos, especialistas y centros de salud de ACUNSA, vinculada a la Clínica Universidad de Navarra.',
                'sort_order' => 30,
            ],
        ];

        $now = now();

        foreach ($insurers as $insurer) {
            DB::table('insurers')->updateOrInsert(
                ['slug' => $insurer['slug']],
                array_merge($insurer, [
                    'logo_url' => '/images/logos/' . $insurer['slug'] . '.webp',
                    'is_active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ])
            );
        }
    }
}
